name: Build SonoBus Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y mingw-w64 cmake

      - name: Build Windows version
        run: |
          mkdir -p build
          cd build
          cmake .. \
            -DCMAKE_SYSTEM_NAME=Windows \
            -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc \
            -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ \
            -DCMAKE_INSTALL_PREFIX=install
          cmake --build . --config Release
          cmake --install .
          ls -R install/bin

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sonobus-windows
          path: build/install/bin
